import { Platform, JavaVersion, PluginSettings } from './types';

export const DEFAULT_SETTINGS: PluginSettings = {
  name: "MyAwesomePlugin",
  groupId: "com.example",
  artifactId: "my-awesome-plugin",
  version: "1.0-SNAPSHOT",
  platform: Platform.PAPER,
  mcVersion: "1.20.4",
  javaVersion: JavaVersion.JAVA_17,
  description: "A cool plugin generated by AI.",
  author: "MineGenAI",
  apiKey: "",
  aiModel: "google/gemini-2.0-flash-001"
};

export const MC_VERSIONS = [
  "1.21.x", "1.20.6", "1.20.4", "1.20.1", 
  "1.19.4", "1.18.2", "1.17.1", "1.16.5", 
  "1.12.2", "1.8.8"
];

export const SYSTEM_INSTRUCTION = `
You are an expert Minecraft Plugin Developer specialized in Spigot, Paper, and Velocity API.
Your task is to generate complete, working, and compilable Java code for Minecraft plugins based on user prompts.

**Rules:**
1. **Structure**: Always generate a standard Maven project structure.
   - src/main/java/... (Java files)
   - src/main/resources/... (plugin.yml, velocity-plugin.json, config.yml)
   - pom.xml (Maven dependencies)
2. **Platform Specifics**:
   - If Platform is Spigot/Paper: Use 'plugin.yml' and extend 'JavaPlugin'.
   - If Platform is Velocity: Use 'velocity-plugin.json', @Plugin annotation, and dependency injection.
3. **Dependencies**: Use the correct repositories and dependencies in 'pom.xml' based on the requested API version.
   - Paper: io.papermc.paper:paper-api
   - Spigot: org.spigotmc:spigot-api
   - Velocity: com.velocitypowered:velocity-api
4. **Code Quality**: Write clean, efficient Java code. Handle nulls and events correctly.
5. **Output Format**: You MUST return a JSON object containing an 'explanation' string and a 'files' array.
`;