import React, { useState, useEffect } from 'react';
import { GeneratedProject, GeneratedFile, PluginSettings } from '../types';
import { FileCode, Copy, Check, FolderOpen, Download } from 'lucide-react';
import JSZip from 'jszip';

interface CodeViewerProps {
  project: GeneratedProject | null;
  settings: PluginSettings;
  onProjectUpdate?: (newProject: GeneratedProject) => void;
}

const CodeViewer: React.FC<CodeViewerProps> = ({ project, settings }) => {
  const [selectedFile, setSelectedFile] = useState<GeneratedFile | null>(null);
  const [copied, setCopied] = useState(false);
  
  useEffect(() => {
    if (project && project.files.length > 0) {
      const currentPath = selectedFile?.path;
      const fileExists = project.files.find(f => f.path === currentPath);
      
      if (!selectedFile || !fileExists) {
          // Try to find Main class first, or default to first file
          const mainFile = project.files.find(f => f.path.endsWith('Main.java') || f.path.endsWith('.java')) || project.files[0];
          setSelectedFile(mainFile);
      } else {
          setSelectedFile(fileExists);
      }
    } else {
        setSelectedFile(null);
    }
  }, [project]);

  const handleCopy = () => {
    if (selectedFile) {
      navigator.clipboard.writeText(selectedFile.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadSource = async () => {
    if (!project) return;
    const zip = new JSZip();
    
    // Full Gradle Project Structure
    project.files.forEach(file => {
        zip.file(file.path, file.content);
    });
    
    // Add Gradle Wrapper Scripts (Standard for any generated project)
    zip.file("gradlew", `#!/bin/sh\n# Gradle Wrapper Script\nexec gradle "$@"\n`);
    zip.file("gradlew.bat", `@if "%DEBUG%" == "" @echo off\ngradle %*\n`);
    
    // Add a helpful README on how to build
    zip.file("README.md", 
`# ${settings.name}

Generated by MineGen AI.

## How to Build
1. Ensure you have Java ${settings.javaVersion} installed.
2. Open a terminal in this folder.
3. Run the build command:

   **Windows:**
   \`\`\`
   gradlew.bat build
   \`\`\`

   **Linux/Mac:**
   \`\`\`
   chmod +x gradlew
   ./gradlew build
   \`\`\`

4. Your plugin JAR will be in \`build/libs/\`.
`);
    
    const blob = await zip.generateAsync({type:"blob"});
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${settings.name}-source.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!project) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center bg-gray-900 text-gray-500 h-full p-8 text-center border-l border-gray-800">
        <FileCode className="w-16 h-16 mb-4 opacity-20" />
        <p className="text-lg font-medium">No Code Generated Yet</p>
        <p className="text-sm max-w-md mt-2">Start chatting to generate a Gradle project structure.</p>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col h-full bg-[#1e1e1e] border-l border-gray-800 overflow-hidden relative">
        {/* Header */}
        <div className="h-12 border-b border-gray-700 flex items-center justify-between px-4 bg-[#252526] shrink-0">
            <h3 className="text-sm font-medium text-white flex items-center gap-2">
                <FolderOpen className="w-4 h-4 text-mc-accent" />
                {settings.name} <span className="text-gray-500 text-xs">({settings.version})</span>
            </h3>
            
            <div className="flex items-center gap-2">
                <button 
                  onClick={handleDownloadSource}
                  className="text-xs bg-mc-accent hover:bg-blue-600 text-white font-semibold px-4 py-1.5 rounded flex items-center gap-2 transition-colors shadow-lg shadow-blue-900/20"
                  title="Download Project Source (ZIP)"
                >
                    <Download className="w-3 h-3" /> Download Source
                </button>
            </div>
        </div>

      <div className="flex-1 flex overflow-hidden">
        {/* File Tree Sidebar */}
        <div className="w-60 bg-[#252526] border-r border-gray-700 overflow-y-auto flex-shrink-0 custom-scrollbar">
          <div className="py-2">
            {project.files.map((file, index) => {
               const fileName = file.path.split('/').pop();
               const isSelected = selectedFile?.path === file.path;
               let iconColor = 'text-gray-400';
               if (fileName?.endsWith('.java')) iconColor = 'text-orange-400';
               else if (fileName?.endsWith('.gradle')) iconColor = 'text-blue-400';
               else if (fileName?.endsWith('.yml') || fileName?.endsWith('.json')) iconColor = 'text-yellow-400';

               return (
                <button
                    key={index}
                    onClick={() => setSelectedFile(file)}
                    className={`w-full text-left px-4 py-1.5 text-sm flex items-center gap-2 truncate hover:bg-[#2a2d2e] transition-colors ${isSelected ? 'bg-[#37373d] text-white border-l-2 border-mc-accent' : 'text-gray-400 border-l-2 border-transparent'}`}
                >
                    <FileCode className={`w-4 h-4 ${iconColor}`} />
                    <span className="truncate" title={file.path}>{fileName}</span>
                </button>
               )
            })}
          </div>
        </div>

        {/* Code Editor Area */}
        <div className="flex-1 flex flex-col min-w-0 bg-[#1e1e1e]">
            {selectedFile ? (
                <>
                    <div className="h-9 flex items-center justify-between px-4 bg-[#1e1e1e] border-b border-gray-800 shrink-0">
                        <span className="text-xs text-gray-400 font-mono">{selectedFile.path}</span>
                        <div className="flex items-center gap-3">
                          <button 
                              onClick={handleCopy}
                              className="text-gray-400 hover:text-white transition-colors"
                              title="Copy Code"
                          >
                              {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                          </button>
                        </div>
                    </div>
                    <div className="flex-1 overflow-auto p-4 custom-scrollbar">
                        <pre className="font-mono text-sm text-gray-300 leading-relaxed">
                            <code>{selectedFile.content}</code>
                        </pre>
                    </div>
                </>
            ) : (
                <div className="flex items-center justify-center h-full text-gray-500 flex-col gap-3">
                    <p>Select a file to view content</p>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default CodeViewer;